Sys.setlocale("LC_TIME", "English")
da<-read.table("household_power_consumption_clean.txt", header=TRUE) ##read data
c<-as.Date(da$Date, format='%d.%m.%Y')
datetime<-as.POSIXct(paste(da$Date, da$Time), format='%d.%m.%Y %H:%M:%S')
png(filename = 'plot4.png', width = 480, height = 480, units = 'px')
par(mfrow=c(2,2))
plot(datetime, da$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(datetime, da$Voltage, type="l",ylab="Voltage")
plot(datetime, da$Sub_metering_1, type="l", col="black",xlab="", ylab="Energy sub metering")
lines(datetime, da$Sub_metering_2, col="red")
lines(datetime, da$Sub_metering_3, col="blue")
legend("topright", pch="-", col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty = "n")
#legend("topright", pch="-", col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty = "n")
plot(datetime, da$Global_reactive_power, type="l", ylab="Global_reactive_power")
dev.off()
